namespace Elaris.Application.Features.Media.Models;

public sealed class MediaAuthenticityOptions
{
    public const string SectionName = "Elaris:MediaAuthenticity";

    /// <summary>
    /// When true, stub/heuristic detectors that cannot decide will treat media as authentic.
    /// Set false only when a real AI-detection provider is wired and required.
    /// </summary>
    public bool AllowWhenUndetermined { get; set; } = true;

    /// <summary>Dev-only: force reject all media as AI-generated.</summary>
    public bool StubForceAiDetected { get; set; }

    /// <summary>Metadata / EXIF / embedded-text markers that suggest generative AI tools.</summary>
    public string[] AiToolMarkers { get; set; } =
    [
        "midjourney",
        "dall-e",
        "dalle",
        "openai",
        "stable diffusion",
        "stablediffusion",
        "novelai",
        "invokeai",
        "comfyui",
        "automatic1111",
        "leonardo.ai",
        "leonardoai",
        "firefly",
        "ideogram",
        "flux.1",
        "flux1",
        "runway",
        "pika labs",
        "sora",
        "synthetic",
        "generated by ai",
        "created with ai",
        "this image was created using ai"
    ];
}
