services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: elaris
      POSTGRES_PASSWORD: elaris
      POSTGRES_DB: elaris
    ports:
      - "5432:5432"
    volumes:
      - elaris_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ELARIS_DB_CONNECTION: Host=postgres;Port=5432;Database=elaris;Username=elaris;Password=elaris
      ELARIS_REDIS: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  elaris_pg:
